project_name: stale-flag-detector
builds:
  - main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
release:
  github:
    owner: kromiii
    name: stale-flag-detector
changelog:
  use: git
