name: "Stale Flag Detector"
description: "Detects potentially stale flags in your unleash project"
author: "kromiii"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  unleash-api-endpoint:
    description: "The URL of the Unleash API (eg. https://unleash.example.com/api)"
    required: true
  unleash-api-token:
    description: "The API token to use to authenticate against the Unleash API (require admin scope)"
    required: true
  unleash-project-id:
    description: "The ID of the Unleash project to check"
    required: false
    default: "default"
  output-format:
    description: "The format of the output (markdown-unordered-list, markdown-task-list, or regex)"
    required: false
    default: "regex"

outputs:
  flags:
    description: "Detected stale flags (in regular expression)"
    value: ${{ steps.run_detector.outputs.flags }}

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
        
    - name: Build
      shell: bash
      run: |
        go build -o stale-flag-detector
        chmod +x stale-flag-detector

    - name: Run stale flag detector
      id: run_detector
      shell: bash
      env:
        UNLEASH_API_ENDPOINT: ${{ inputs.unleash-api-endpoint }}
        UNLEASH_API_TOKEN: ${{ inputs.unleash-api-token }}
        UNLEASH_PROJECT_ID: ${{ inputs.unleash-project-id }}
      run: |
        OUTPUT=$(./stale-flag-detector --output-format ${{ inputs.output-format }})
        if [[ "$OUTPUT" == "No stale flags"* ]]; then
          echo "No stale flags detected. Exiting."
          echo "flags=" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "flags=$OUTPUT" >> $GITHUB_OUTPUT
