name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: stale-flag-detector
        uses: ./ # 同一リポジトリ内のアクションを参照
        with:
          unleash-api-endpoint: ${{ secrets.UNLEASH_API_ENDPOINT }}
          unleash-api-token: ${{ secrets.UNLEASH_API_TOKEN }}
      - run: |
          echo ${{ steps.stale-flag-detector.outputs.flags }}
