name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: stale-flag-detector
        uses: ./ # Directly use the action
        with:
          unleash-api-endpoint: ${{ secrets.UNLEASH_API_ENDPOINT }}
          unleash-api-token: ${{ secrets.UNLEASH_API_TOKEN }}
          output-format: markdown-task-list
      - name: Decode escaped output
        run: |
          DECODED_OUTPUT=$(echo "${{ steps.stale-flag-detector.outputs.flags }}" | sed 's/%25/%/g; s/%0A/\n/g; s/%0D/\r/g')
          echo "Decoded Output:"
          echo "$DECODED_OUTPUT"
